services:
  kafka-01:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka_01
    ports:
      - "9092:10000"
    environment:
      CLUSTER_ID: "90546ce1-ad47-4986-807b-70d39b1a544f"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_LISTENER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER_LISTENER
      KAFKA_LISTENERS:
        BROKER_LISTENER://:9092,
        CONTROLLER_LISTENER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS:
        1@kafka-01:9093,
        2@kafka-02:9093,
        3@kafka-03:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER_LISTENER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        BROKER_LISTENER:PLAINTEXT,
        CONTROLLER_LISTENER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-01-data:/var/lib/kafka/data

  kafka-02:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka_02
    ports:
      - "9094:10000"
    environment:
      CLUSTER_ID: "90546ce1-ad47-4986-807b-70d39b1a544f"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_LISTENER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER_LISTENER
      KAFKA_LISTENERS:
        BROKER_LISTENER://:9092,
        CONTROLLER_LISTENER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS:
        1@kafka-01:9093,
        2@kafka-02:9093,
        3@kafka-03:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER_LISTENER://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        BROKER_LISTENER:PLAINTEXT,
        CONTROLLER_LISTENER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-02-data:/var/lib/kafka/data

  kafka-03:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka_03
    ports:
      - "9096:10000"
    environment:
      CLUSTER_ID: "90546ce1-ad47-4986-807b-70d39b1a544f"
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_LISTENER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER_LISTENER
      KAFKA_LISTENERS:
        BROKER_LISTENER://:9092,
        CONTROLLER_LISTENER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS:
        1@kafka-01:9093,
        2@kafka-02:9093,
        3@kafka-03:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER_LISTENER://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        BROKER_LISTENER:PLAINTEXT,
        CONTROLLER_LISTENER:PLAINTEXT
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-03-data:/var/lib/kafka/data

  db-01:
    image: mysql:9.6.0
    container_name: mysql-db-01
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - some-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  some-network:
    driver: bridge

volumes:
  kafka-01-data:
  kafka-02-data:
  kafka-03-data:
  mysql-data: